### ISSUE TITLE
Could not login

### ISSUE THREAD

**Issue by hejiann** [ginuerzh/uqq#1]
$ qmlscene -I plugin uqq.qml
check code... 
"http://check.ptlogin2.qq.com/check?uin=xxxxxx&appid=1003903&r=0.00010026657773536" 
check code done, code no needed. 
QIODevice::write: device not open
request login... 
"http://ptlogin2.qq.com/login?u=xxxxxx&p=xxxxxx&verifycode=!GTK&aid=1003903&webqq_type=10&remember_uin=0&login2qq=1&h=1&ptredirect=0&ptlang=2052&from_ui=1&pttype=1&fp=loginerroralert&action=2-6-22950&mibao_css=m_webqq&t=1&g=1&u1=http%3A%2F%2Fweb.qq.com%2Floginproxy.html%3Flogin2qq%3D1%26webqq_type%3D10" 
login done. 
request second login... 
"http://d.web2.qq.com/channel/login2" 
ptwebqq: "ded7931a0ad929bff76fc58edeadca233ef6d408412f0dc4b06f2e41e79ae199" 
verify second login...

**Comment by ginuerzh** [comment]
this project has been deprecated, I will no longer maintain it.
